#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from wsgiref.simple_server import make_server
from inspect import getmembers,isfunction
from functools import wraps

class Manakanemu:
    def __init__(self,host='',port=80):
        self.port = port
        self.host = host
        self.httpd = make_server(host=self.host,port=self.port,app=self.application)
        self.function = [x[-1] for x in getmembers(__import__('url'),isfunction) if x not in getmembers(__import__('method'))]


    def application(self,environ, start_response):
        result = None
        print('path: '+environ['PATH_INFO']+' Method:'+environ['REQUEST_METHOD'])
        for fun in self.function:
            result = fun(environ)
            if isinstance(result,str):
                start_response('200 OK', [('Content-Type', 'text/html')])
                return [bytes(result,'utf-8')]
                break

        start_response('404 OK', [('Content-Type', 'text/html')])
        return [b'404 NOT FOUND']

    def run(self):
        print('Manakanemu is running on http://localhost:'+str(self.port))
        self.httpd.serve_forever()




M = Manakanemu()
M.run()




